import '../models/category_model.dart';
import '../models/ingredient_model.dart';
import '../models/recipe_model.dart';

class DummyData {
  static final List<CategoryModel> initialCategories = [
    const CategoryModel(id: 'all', name: 'All', icon: '🍽️'),
    const CategoryModel(id: 'curry', name: 'Curry', icon: '🍛'),
    const CategoryModel(id: 'italian', name: 'Italian', icon: '🍕'),
    const CategoryModel(id: 'breakfast', name: 'Breakfast', icon: '🍳'),
    const CategoryModel(id: 'healthy', name: 'Healthy', icon: '🥗'),
    const CategoryModel(id: 'dessert', name: 'Dessert', icon: '🍰'),
    const CategoryModel(id: 'asian', name: 'Asian', icon: '🍜'),
  ];

  static final List<Recipe> initialRecipes = [
    Recipe(
      id: 'rec_1',
      title: 'Paneer Butter Masala',
      category: 'Curry',
      imageUrl: 'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=1000&q=80',
      prepTimeMinutes: 25,
      calories: 420,
      rating: 4.8,
      reviewCount: 38,
      baseServings: 2,
      isFavorite: true,
      ingredients: const [
        Ingredient(name: 'Paneer Cubes', amount: 400, unit: 'g'),
        Ingredient(name: 'Butter', amount: 50, unit: 'g'),
        Ingredient(name: 'Heavy Cream', amount: 60, unit: 'ml'),
        Ingredient(name: 'Ripe Tomatoes', amount: 4, unit: 'pcs'),
        Ingredient(name: 'Cashew Nuts', amount: 15, unit: 'pcs'),
        Ingredient(name: 'Ginger-Garlic Paste', amount: 1.5, unit: 'tbsp'),
        Ingredient(name: 'Garam Masala', amount: 1, unit: 'tsp'),
        Ingredient(name: 'Kasuri Methi', amount: 1, unit: 'tsp'),
        Ingredient(name: 'Kashmiri Chili Powder', amount: 1, unit: 'tbsp'),
      ],
      instructions: [
        'Boil sliced tomatoes and soaked cashews in water for 10 minutes until soft, then blend into a silky smooth puree.',
        'Melt 25g butter in a heavy pan. Add whole spices and ginger-garlic paste; sauté for 1 minute until fragrant.',
        'Pour in the tomato cashew puree and simmer on low-medium heat for 8-10 minutes until oil begins to release.',
        'Add red chili powder, garam masala, salt, and remaining butter. Stir gently.',
        'Add paneer cubes and warm water to adjust gravy consistency. Simmer for 4-5 minutes.',
        'Finish with crushed kasuri methi and fresh heavy cream. Serve hot with buttery naan or jeera rice.',
      ],
    ),
    Recipe(
      id: 'rec_2',
      title: 'Artisan Margherita Pizza',
      category: 'Italian',
      imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=1000&q=80',
      prepTimeMinutes: 30,
      calories: 580,
      rating: 4.9,
      reviewCount: 52,
      baseServings: 2,
      isFavorite: true,
      ingredients: const [
        Ingredient(name: 'Pizza Dough Ball', amount: 300, unit: 'g'),
        Ingredient(name: 'San Marzano Tomatoes', amount: 150, unit: 'g'),
        Ingredient(name: 'Fresh Mozzarella', amount: 200, unit: 'g'),
        Ingredient(name: 'Fresh Basil Leaves', amount: 10, unit: 'leaves'),
        Ingredient(name: 'Extra Virgin Olive Oil', amount: 2, unit: 'tbsp'),
        Ingredient(name: 'Sea Salt', amount: 1, unit: 'pinch'),
      ],
      instructions: [
        'Preheat your oven with a pizza stone at its maximum temperature (around 250°C / 480°F) for 45 minutes.',
        'Stretch the dough gently by hand from center to edges on a lightly floured surface, leaving an airy crust border.',
        'Crush San Marzano tomatoes with sea salt and spread evenly over the base.',
        'Tear fresh mozzarella into chunks and distribute evenly across the tomato sauce.',
        'Slide pizza into the oven and bake for 7 to 9 minutes until crust is blistered and cheese is melted.',
        'Garnish immediately with fresh basil leaves and a generous drizzle of olive oil before slicing.',
      ],
    ),
    Recipe(
      id: 'rec_3',
      title: 'Tokyo Shoyu Ramen',
      category: 'Asian',
      imageUrl: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1000&q=80',
      prepTimeMinutes: 35,
      calories: 610,
      rating: 4.7,
      reviewCount: 29,
      baseServings: 2,
      isFavorite: false,
      ingredients: const [
        Ingredient(name: 'Fresh Ramen Noodles', amount: 250, unit: 'g'),
        Ingredient(name: 'Rich Chicken Broth', amount: 800, unit: 'ml'),
        Ingredient(name: 'Soy Sauce (Shoyu tare)', amount: 4, unit: 'tbsp'),
        Ingredient(name: 'Chashu Pork or Tofu', amount: 4, unit: 'slices'),
        Ingredient(name: 'Soft-boiled Ajitsuke Egg', amount: 2, unit: 'pcs'),
        Ingredient(name: 'Bamboo Shoots (Menma)', amount: 50, unit: 'g'),
        Ingredient(name: 'Nori Seaweed', amount: 2, unit: 'sheets'),
        Ingredient(name: 'Scallions / Spring Onions', amount: 2, unit: 'stalks'),
      ],
      instructions: [
        'Prepare the shoyu tare seasoning base by mixing high-grade soy sauce, mirin, and dashi in serving bowls.',
        'Bring the savory chicken broth to a gentle simmer in a dedicated saucepan.',
        'Boil fresh ramen noodles in a separate pot of rapidly boiling water for 90 seconds until al dente.',
        'Pour hot broth into the bowls with tare, whisking gently to combine.',
        'Strain noodles thoroughly and fold neatly into the broth.',
        'Top with sliced chashu, halved marinated egg, menma, scallions, and crisp nori.',
      ],
    ),
    Recipe(
      id: 'rec_4',
      title: 'Smoked Salmon Avocado Toast',
      category: 'Breakfast',
      imageUrl: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1000&q=80',
      prepTimeMinutes: 12,
      calories: 340,
      rating: 4.6,
      reviewCount: 19,
      baseServings: 1,
      isFavorite: false,
      ingredients: const [
        Ingredient(name: 'Artisan Sourdough', amount: 2, unit: 'slices'),
        Ingredient(name: 'Ripe Hass Avocado', amount: 1, unit: 'pc'),
        Ingredient(name: 'Smoked Salmon', amount: 100, unit: 'g'),
        Ingredient(name: 'Fresh Lemon Juice', amount: 1, unit: 'tsp'),
        Ingredient(name: 'Red Onion Slices', amount: 20, unit: 'g'),
        Ingredient(name: 'Everything Bagel Seasoning', amount: 1, unit: 'tsp'),
        Ingredient(name: 'Microgreens / Dill', amount: 10, unit: 'g'),
      ],
      instructions: [
        'Toast sourdough bread slices until golden brown and audibly crisp.',
        'In a bowl, coarsely mash the ripe avocado with lemon juice, salt, and black pepper.',
        'Spread the mashed avocado generously onto the warm toasted sourdough.',
        'Drape delicate slices of smoked salmon over the avocado base.',
        'Garnish with thin red onion slivers, fragrant fresh dill or microgreens, and everything bagel seasoning.',
      ],
    ),
    Recipe(
      id: 'rec_5',
      title: 'Mediterranean Quinoa Salad',
      category: 'Healthy',
      imageUrl: 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=80',
      prepTimeMinutes: 18,
      calories: 290,
      rating: 4.8,
      reviewCount: 44,
      baseServings: 2,
      isFavorite: false,
      ingredients: const [
        Ingredient(name: 'Cooked Quinoa', amount: 200, unit: 'g'),
        Ingredient(name: 'Cherry Tomatoes', amount: 120, unit: 'g'),
        Ingredient(name: 'English Cucumber', amount: 1, unit: 'pc'),
        Ingredient(name: 'Kalamata Olives', amount: 50, unit: 'g'),
        Ingredient(name: 'Crumbled Feta Cheese', amount: 75, unit: 'g'),
        Ingredient(name: 'Extra Virgin Olive Oil', amount: 3, unit: 'tbsp'),
        Ingredient(name: 'Lemon Herb Dressing', amount: 2, unit: 'tbsp'),
      ],
      instructions: [
        'Rinse and fluff the pre-cooked cooled quinoa in a wide salad mixing bowl.',
        'Dice cucumbers and halve the fresh sweet cherry tomatoes.',
        'Add diced vegetables, kalamata olives, and chopped fresh mint or parsley to the quinoa.',
        'Whisk together extra virgin olive oil, lemon juice, minced garlic, oregano, and sea salt in a small bowl.',
        'Drizzle vinaigrette over the salad and toss gently to coat evenly.',
        'Top with crumbled Greek feta cheese before serving chilled.',
      ],
    ),
    Recipe(
      id: 'rec_6',
      title: 'Molten Belgian Chocolate Lava Cake',
      category: 'Dessert',
      imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=1000&q=80',
      prepTimeMinutes: 22,
      calories: 490,
      rating: 4.9,
      reviewCount: 63,
      baseServings: 2,
      isFavorite: true,
      ingredients: const [
        Ingredient(name: 'Dark Chocolate (70%)', amount: 120, unit: 'g'),
        Ingredient(name: 'Unsalted Butter', amount: 80, unit: 'g'),
        Ingredient(name: 'Large Eggs', amount: 2, unit: 'pcs'),
        Ingredient(name: 'Powdered Sugar', amount: 50, unit: 'g'),
        Ingredient(name: 'All-Purpose Flour', amount: 30, unit: 'g'),
        Ingredient(name: 'Pure Vanilla Extract', amount: 1, unit: 'tsp'),
      ],
      instructions: [
        'Grease two ceramic ramekins generously with butter and dust lightly with cocoa powder.',
        'Melt the dark chocolate and butter together in a heatproof bowl set over a pot of simmering water.',
        'Whisk eggs, egg yolks, and powdered sugar in a separate bowl until pale and frothy.',
        'Gently fold the melted chocolate mixture and flour into the eggs until a glossy batter forms.',
        'Divide batter between the ramekins and bake at 200°C (390°F) for exactly 11-12 minutes.',
        'Run a thin knife around edges, invert onto dessert plates, and dust with powdered sugar. Serve with vanilla bean gelato.',
      ],
    ),
  ];
}
